### ISSUE TITLE
Contact repository owner personally.

### ISSUE THREAD

**Issue by U65535F** [wufhex/FileWatson-FileSearchTool#1]
Hi. 
This is not related to the repository in any way.
I want to contact @wufhex, so is there any way to do so? Like discord or email?
I assume that @wufhex's previous username is WolfHex and had a YouTube channel in past that got terminated.

Thank you.

**Comment by wufhex** [comment]
Yes that's my username, I think I might refused your request as a bot account, send it again.

**Comment by U65535F** [comment]
My friend request is still not getting accepted. 
Username: cd255
